--- 
title: "Kompendium zum wissenschaftlichen Arbeiten"
description: ""
author: "Thomas Janßen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
graphics: yes
documentclass: scrbook
classoption: oneside,12pt,a4paper
lang: de
output:
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    citation_package: biblatex
    template: null
bibliography: [literatur.bib]
csl: apa-de.csl
biblatexoptions: [refsegment=chapter]
link-citations: yes
biblio-style: apa
---

# Vorwort {-}

Liebe Student\_innen,

in Anlehnung an den Studiengang Politikwissenschaft, der seinen Studierenden schon seit mehreren Jahren ein Kompendium zum Wissenschaftlichen Arbeiten an die Hand gibt [@autorengruppe2012], haben auch wir in der AG Didaktik es uns zum Ziel gesetzt, ein solches Machwerk zu erstellen.

Primäre Motivation war es, Ihnen eine verlässliche Information darüber zu geben, welche wissenschaftlichen Standards wir in der AG Didaktik für selbstverständlich halten und dementsprechend in Haus-, Bachelor- und Masterarbeiten anlegen. Nach einer Vorstellung der AG besteht der Kern dieses Kompendiums daher in einer Kurzanleitung zum richtigen Zitieren. Zusätzlich haben wir einige Informationen zusammengestellt, die Ihnen helfen können, nicht nur formal korrekte, sondern auch wirklich gute Arbeiten zu schreiben: Sie finden einen Leitfaden zum Schreiben von Hausarbeiten, einen kurzen Überblick darüber, was Sie beachten müssen, wenn Sie mit personenbezogenen Daten (etwa von Schüler\_innen) arbeiten, sowie eine Auflistung von Online-Ressourcen, die Ihnen den Zugang zur Mathematikdidaktik erleichtern können.

Das Kompendium kann und soll im praktischen Gebrauch reifen, und so freuen wir uns über Hinweise darauf, welche Informationen unter Umständen noch fehlen. Sprechen Sie mich gerne persönlich an oder schreiben Sie mir eine E-Mail an <janssent@uni-bremen.de>.

Ein Punkt, der im Kompendium nicht angesprochen wird, ist der der geschlechtergerechten Sprache. Es ist der Universität Bremen ein Anliegen, darauf zu achten, dass niemand durch die Wahl der sprachlichen Mittel ausgeschlossen wird. Dazu, wie dies geschieht, machen wir hier keine Vorgaben. In diesem Dokument werden jedoch entweder genderneutrale Begriffe oder die Unterstrich-Schreibweise verwendet. Bei ihr fügt man zwischen männlicher und weiblicher Form einen Unterstrich ein, um darauf hinzuweisen, dass auch geschlechtliche Identitäten mitgedacht werden, die durch das dualistische Konzept von Mann und Frau nicht erfasst werden. Manchmal stößt diese Methode jedoch an ihre Grenzen, etwa wenn mehrere Wörter gebeugt werden. Hier wurde in diesen Fällen auf die klassische Schrägstrich-Schreibweise zurückgegriffen. Dies kann Ihnen vielleicht als Anschauung und Entscheidungshilfe bei der Entwicklung Ihres eigenen Stils dienen.

Viel Freude und Erfolg im Studium wünscht Ihnen im Namen aller Mitglieder der AG Didaktik

Thomas Janßen
